export interface LyricLine {
  time: number // seconds
  text: string
}

export interface Song {
  id: string
  title: string
  artist: string
  audioUrl: string
  cover?: string
  lyrics: LyricLine[]
}

export const playlist: Song[] = [
  {
    id: "2707652860",
    title: "半句再见",
    artist: "孙燕姿",
    audioUrl: "/audio/banjuzaijian.mp3",
    lyrics: [
      { time: 0, text: "半句再见 - 孙燕姿" },
      { time: 5, text: "词：徐佳莹" },
      { time: 9, text: "曲：徐佳莹" },
      { time: 14, text: "" },
      { time: 17, text: "还记得那年夏天" },
      { time: 21, text: "你说你要走" },
      { time: 25, text: "我站在车站里" },
      { time: 29, text: "看着你的背影" },
      { time: 33, text: "" },
      { time: 36, text: "半句再见" },
      { time: 40, text: "说不出口的眷恋" },
      { time: 44, text: "你微笑着挥挥手" },
      { time: 48, text: "转身消失在人海中" },
      { time: 52, text: "" },
      { time: 55, text: "如果当时勇敢一点" },
      { time: 59, text: "如果当时执着一点" },
      { time: 63, text: "是不是故事结局" },
      { time: 67, text: "会有不同的终点" },
      { time: 71, text: "" },
      { time: 74, text: "半句再见" },
      { time: 78, text: "藏在心里多少年" },
      { time: 82, text: "偶尔想起你的脸" },
      { time: 86, text: "依然会红了眼" },
      { time: 90, text: "" },
      { time: 93, text: "时间走得好远" },
      { time: 97, text: "我们都在改变" },
      { time: 101, text: "只是那句没说完的再见" },
      { time: 105, text: "还在心里盘旋" },
      { time: 110, text: "" },
      { time: 113, text: "半句再见" },
      { time: 117, text: "成了永远的遗憾" },
      { time: 121, text: "愿你过得好" },
      { time: 125, text: "在没有我的世界" },
      { time: 130, text: "" },
      { time: 133, text: "（间奏）" },
      { time: 160, text: "" },
      { time: 165, text: "还记得那个夏天" },
      { time: 169, text: "那句没说完的再见" },
      { time: 175, text: "半句再见" },
    ],
  },
  {
    id: "3403344548",
    title: "Cry for me",
    artist: "Michita",
    audioUrl: "/audio/cry-for-me.mp3",
    lyrics: [
      { time: 0, text: "Cry for me - Michita" },
      { time: 10, text: "" },
      { time: 15, text: "Tell me that you'll cry for me" },
      { time: 20, text: "Even though you say goodbye" },
      { time: 25, text: "Tell me that you'll cry for me" },
      { time: 30, text: "I don't wanna say goodbye" },
      { time: 35, text: "" },
      { time: 40, text: "夜が明ける前" },
      { time: 45, text: "君の声が聞こえる" },
      { time: 50, text: "涙が止まらない" },
      { time: 55, text: "Cry for me tonight" },
      { time: 60, text: "" },
      { time: 65, text: "Tell me that you'll cry for me" },
      { time: 70, text: "Even though you say goodbye" },
      { time: 75, text: "Tell me that you'll cry for me" },
      { time: 80, text: "I don't wanna say goodbye" },
      { time: 85, text: "" },
      { time: 90, text: "（间奏）" },
      { time: 120, text: "" },
      { time: 125, text: "Cry for me" },
      { time: 130, text: "Tell me that you'll cry for me" },
    ],
  },
  {
    id: "1989506149",
    title: "最好的时光",
    artist: "安溥",
    audioUrl: "/audio/best-time.mp3",
    lyrics: [
      { time: 0, text: "最好的时光 - 安溥" },
      { time: 8, text: "" },
      { time: 12, text: "最好的时光" },
      { time: 16, text: "是和你在一起" },
      { time: 20, text: "最好的时光" },
      { time: 24, text: "是看着你的眼睛" },
      { time: 28, text: "" },
      { time: 32, text: "那些年少的轻狂" },
      { time: 36, text: "那些不灭的梦" },
      { time: 40, text: "都留在最好的时光里" },
      { time: 44, text: "" },
      { time: 48, text: "最好的时光" },
      { time: 52, text: "不曾走远" },
      { time: 56, text: "最好的时光" },
      { time: 60, text: "就在你我之间" },
      { time: 64, text: "" },
      { time: 68, text: "最好的时光" },
      { time: 72, text: "是你微笑的脸" },
      { time: 76, text: "最好的时光" },
      { time: 80, text: "我们不曾走散" },
      { time: 84, text: "" },
      { time: 88, text: "（间奏）" },
      { time: 120, text: "" },
      { time: 124, text: "最好的时光" },
      { time: 128, text: "最好的时光" },
    ],
  },
  {
    id: "2154520553",
    title: "Marry Top Barry",
    artist: "INDEcompany",
    audioUrl: "/audio/marry-top-barry.mp3",
    lyrics: [
      { time: 0, text: "Marry Top Barry - INDEcompany" },
      { time: 10, text: "" },
      { time: 15, text: "（纯音乐）" },
      { time: 60, text: "" },
      { time: 120, text: "" },
      { time: 180, text: "" },
    ],
  },
  {
    id: "569200210",
    title: "给你给我",
    artist: "毛不易",
    audioUrl: "/audio/give-you-give-me.mp3",
    lyrics: [
      { time: 0, text: "给你给我 - 毛不易" },
      { time: 6, text: "" },
      { time: 10, text: "给你给我" },
      { time: 14, text: "给你我的所有" },
      { time: 18, text: "给你给我" },
      { time: 22, text: "给你我的温柔" },
      { time: 26, text: "" },
      { time: 30, text: "你说你想去看海" },
      { time: 34, text: "我就陪你去看海" },
      { time: 38, text: "你说你想看星空" },
      { time: 42, text: "我就陪你数星星" },
      { time: 46, text: "" },
      { time: 50, text: "给你给我" },
      { time: 54, text: "给你我的执着" },
      { time: 58, text: "给你给我" },
      { time: 62, text: "给你我的承诺" },
      { time: 66, text: "" },
      { time: 70, text: "给你我的手" },
      { time: 74, text: "陪你走过每个春秋" },
      { time: 78, text: "给你我的心" },
      { time: 82, text: "陪你度过每个冬夏" },
      { time: 86, text: "" },
      { time: 90, text: "给你给我" },
      { time: 94, text: "给你我的所有" },
      { time: 98, text: "给你给我" },
      { time: 102, text: "给你我的温柔" },
      { time: 106, text: "" },
      { time: 110, text: "（间奏）" },
      { time: 140, text: "" },
      { time: 144, text: "给你给我" },
      { time: 148, text: "给你我的所有" },
    ],
  },
  {
    id: "2146002926",
    title: "不要说话",
    artist: "陈奕迅",
    audioUrl: "/audio/buyao-shuohua.mp3",
    lyrics: [
      { time: 0, text: "不要说话 - 陈奕迅" },
      { time: 10, text: "" },
      { time: 15, text: "习惯了不说" },
      { time: 19, text: "习惯了沉默" },
      { time: 23, text: "习惯了一个人走" },
      { time: 27, text: "" },
      { time: 31, text: "不要说话" },
      { time: 35, text: "让我静静看着你" },
      { time: 39, text: "不要说话" },
      { time: 43, text: "让我默默陪着你" },
      { time: 47, text: "" },
      { time: 51, text: "爱不是说得出口" },
      { time: 55, text: "是为你守候" },
      { time: 59, text: "不要说话" },
      { time: 63, text: "" },
      { time: 67, text: "（间奏）" },
      { time: 100, text: "" },
      { time: 105, text: "不要说话" },
      { time: 109, text: "让我静静看着你" },
      { time: 113, text: "不要说话" },
      { time: 117, text: "让我默默陪着你" },
    ],
  },
  {
    id: "2099014638",
    title: "在你的身边 (伴奏)",
    artist: "盛哲",
    audioUrl: "/audio/ni-shenbian.mp3",
    lyrics: [
      { time: 0, text: "在你的身边 (伴奏) - 盛哲" },
      { time: 10, text: "" },
      { time: 15, text: "（伴奏）" },
      { time: 60, text: "" },
      { time: 120, text: "" },
      { time: 180, text: "" },
    ],
  },
  {
    id: "432698831",
    title: "我离孤单几公里",
    artist: "华晨宇",
    audioUrl: "/audio/guli.mp3",
    lyrics: [
      { time: 0, text: "我离孤单几公里 - 华晨宇" },
      { time: 8, text: "" },
      { time: 12, text: "我离孤单几公里" },
      { time: 16, text: "走着走着就散了" },
      { time: 20, text: "我离孤单几公里" },
      { time: 24, text: "想着想着就淡了" },
      { time: 28, text: "" },
      { time: 32, text: "沿途的风景" },
      { time: 36, text: "都与我无关" },
      { time: 40, text: "只有你的笑脸" },
      { time: 44, text: "还在脑海转" },
      { time: 48, text: "" },
      { time: 52, text: "我离孤单几公里" },
      { time: 56, text: "也许就在你身边" },
      { time: 60, text: "我离孤单几公里" },
      { time: 64, text: "也许你已走远" },
      { time: 68, text: "" },
      { time: 72, text: "（间奏）" },
      { time: 110, text: "" },
      { time: 115, text: "我离孤单几公里" },
    ],
  },
  {
    id: "2161934816",
    title: "向阳而生",
    artist: "华晨宇",
    audioUrl: "/audio/xiangyang.mp3",
    lyrics: [
      { time: 0, text: "向阳而生 - 华晨宇" },
      { time: 8, text: "" },
      { time: 12, text: "向阳而生" },
      { time: 16, text: "逆风而行" },
      { time: 20, text: "每一道伤痕" },
      { time: 24, text: "都是勋章" },
      { time: 28, text: "" },
      { time: 32, text: "向阳而生" },
      { time: 36, text: "不惧黑暗" },
      { time: 40, text: "心中有光" },
      { time: 44, text: "何惧远方" },
      { time: 48, text: "" },
      { time: 52, text: "就算跌倒" },
      { time: 56, text: "也要仰望" },
      { time: 60, text: "就算流泪" },
      { time: 64, text: "也要坚强" },
      { time: 68, text: "" },
      { time: 72, text: "向阳而生" },
      { time: 76, text: "这就是我的模样" },
      { time: 80, text: "" },
      { time: 84, text: "（间奏）" },
      { time: 120, text: "" },
      { time: 124, text: "向阳而生" },
    ],
  },
  {
    id: "394485",
    title: "思念是一种病 (live)",
    artist: "张震岳",
    audioUrl: "/audio/sinian.mp3",
    lyrics: [
      { time: 0, text: "思念是一种病 - 张震岳" },
      { time: 10, text: "" },
      { time: 15, text: "当你在穿山越岭的另一边" },
      { time: 20, text: "我在孤独的路上没有尽头" },
      { time: 25, text: "时常感觉你在耳后的呼吸" },
      { time: 30, text: "却未曾感觉你在心口的鼻息" },
      { time: 35, text: "" },
      { time: 40, text: "思念是一种病" },
      { time: 45, text: " oh 思念是一种病" },
      { time: 50, text: "一种病" },
      { time: 55, text: "" },
      { time: 60, text: "当你在穿山越岭的另一边" },
      { time: 65, text: "我在孤独的路上没有尽头" },
      { time: 70, text: "时常感觉你在耳后的呼吸" },
      { time: 75, text: "却未曾感觉你在心口的鼻息" },
      { time: 80, text: "" },
      { time: 85, text: "思念是一种病" },
      { time: 90, text: "oh 思念是一种病" },
      { time: 95, text: "" },
      { time: 100, text: "（间奏）" },
      { time: 140, text: "" },
      { time: 145, text: "思念是一种病" },
    ],
  },
]
